export const customFonts = {
  PoppinRegular: require("./Poppins-Regular.otf"),
  PoppinItalic: require("./Poppins-Italic.otf"),
  PoppinThin: require("./Poppins-Thin.otf"),
  PoppinThinItalic: require("./Poppins-ThinItalic.otf"),
  PoppinLight: require("./Poppins-Light.otf"),
  PoppinLightItalic: require("./Poppins-LightItalic.otf"),
  PoppinExtraLight: require("./Poppins-ExtraLight.otf"),
  PoppinExtraLightItalic: require("./Poppins-ExtraLightItalic.otf"),
  PoppinMedium: require("./Poppins-Medium.otf"),
  PoppinMediumItalic: require("./Poppins-MediumItalic.otf"),
  PoppinBold: require("./Poppins-Bold.otf"),
  PoppinBoldItalic: require("./Poppins-BoldItalic.otf"),
  PoppinExtraBold: require("./Poppins-ExtraBold.otf"),
  PoppinExtraBoldItalic: require("./Poppins-ExtraBoldItalic.otf"),
  PoppinSemiBold: require("./Poppins-SemiBold.otf"),
  PoppinSemiBoldItalic: require("./Poppins-SemiBoldItalic.otf"),
  PoppinBlack: require("./Poppins-Black.otf"),
  PoppinBlackItalic: require("./Poppins-BlackItalic.otf"),
};
