import {
  setEmail,
  setPhoneNumber,
  setToken,
  setUser,
  setUsername,
  selectEmail,
  selectPhoneNumber,
  selectToken,
  selectUser,
  selectUsername,
  selectInitialRoute,
  selectFromRoute,
  setFromRoute,
} from "./slices/userSlice";

export {
  setEmail,
  setPhoneNumber,
  setToken,
  setUser,
  setUsername,
  selectEmail,
  selectPhoneNumber,
  selectToken,
  selectUser,
  selectUsername,
  selectInitialRoute,
  selectFromRoute,
  setFromRoute,
};
