name: Node.js CI

on:
  push:
    branches:
      - develop
      - uat
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Update version
        run: npm run update-version
      
       - name: Set Expo Token
        run: echo "EXPO_TOKEN=${{ secrets.GITHUB_EXPO_TOKEN }}" >> $GITHUB_ENV

      - name: Run CI for Dev
        run: |
          export EXPO_TOKEN=${{ secrets.GITHUB_EXPO_TOKEN }}
          npm run ci:dev:simulator && npm run ci:dev
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EXPO_TOKEN: ${{ secrets.GITHUB_EXPO_TOKEN }}

      - name: Run CI for UAT
        run: |
          export EXPO_TOKEN=${{ secrets.GITHUB_EXPO_TOKEN }}
          npm run ci:uat
        if: github.event_name == 'push' && github.ref == 'refs/heads/uat'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EXPO_TOKEN: ${{ secrets.GITHUB_EXPO_TOKEN }}

      - name: Run CI for Prod
        run: |
          export EXPO_TOKEN=${{ secrets.GITHUB_EXPO_TOKEN }}
          npm run ci:prod
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EXPO_TOKEN: ${{ secrets.GITHUB_EXPO_TOKEN }}
